### PR TITLE
Added average_rating method and made it show on the game#show page

### PR DESCRIPTION
**Pull request by rileslovesyall**
I added some Event seeds, so I could test that it was working properly. On the game#show page, it will display the average rating if there is one, and if not, it will display text that says there is no average rating. So if a game does not have any events (or if an event wasn't rated), it won't cause problems. I didn't add that a rating is a required validation for an event, because I wasn't sure if you wanted that or not, but the code as written will work either way.

### CODE REVIEW

**Comment by jennaplusplus** [comment]
fix merge conflict first (may be my fault, sorry). Problem in Gemfile. Fetch upstream from master.

**Comment by rileslovesyall** [comment]
Np. I'll fix it, I remember having to add something to Gemfile.. pry, I
think, for debugging. I'm sure it'll be a quick fix.

**Comment by rileslovesyall** [comment]
fixed and pushed. it should be able to merge now?

**Comment by rileslovesyall** [comment]
#15 is the related issue, FYI

**Comment by jennaplusplus** [comment]
Looks great! One small request: add some kind of rounding for the game show view :)

**Comment by rileslovesyall** [comment]
rounding added!

**Pull request merged**
